apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: authentication-day2-configuration
policyDefaults:
  namespace: my-policies
  policyDefaults.orderManifests: true
  policyDefaults.orderPolicies: true
  remediationAction: inform
policies:
  - name: kubeadmin-remove
    manifests:
      - path: manifests/kubeadmin-pass.yaml
    complianceType: mustnothave
    
